version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "hello-serverless-golang"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3td7909w13da1"
s3_prefix = "hello-serverless-golang"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
